apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: selinkaraman/webapp:b0d9c8d089b59e68879c3106d5a0499cdc845d8a
        ports:
        - containerPort: 3000